version: "3"
services:
    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - /data/pyusic/data:/data
    pyusic-api:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        restart: always
