version: "3"
services:
    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - /data/pyusic/data:/data/db
    pyusic-api:
        image: hongbozhang/pyusic-api
        ports:
            - 5000:5000
        restart: always
